# Generated by Django 6.0.5 on 2026-06-06 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
        ('inventory', '0003_product_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shop'),
        ),
    ]
