# Generated by Django 6.0.5 on 2026-06-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_creditpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
