# Generated by Django 6.0.5 on 2026-06-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
