# Generated by Django 6.0.5 on 2026-06-06 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
        ('sales', '0008_alter_cashiershift_user_alter_sale_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shop'),
        ),
        migrations.AddField(
            model_name='sale',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shop'),
        ),
    ]
